image: node:latest

stages:
  - deploy

runDeploy:
  before_script:
    - npm install
  stage: deploy
  script:
    - npm run production
  artifacts:
    expire_in: 1 week
    paths:
      - $CI_PROJECT_DIR/dist
